### ISSUE TITLE
throughput experiment indefinitely waiting

### ISSUE THREAD

**Issue by Miao-code** [mryab/learning-at-home#1]
Greetings.

I am right now studying your paper and I really like your idea about decentralized deep learning.
I am trying to run your throughput experiment, since I only have one 2080 card, I use:

python throughput_server.py -a 32 -p 1080 --block-type ffn --gpu 0
python throughput_client.py -j 32 --batches-for-latency 5 --batches-for-throughput 2 --throughput-runs 5 --linspace-points 10 --layers-per-gpu 56 --block-type ffn --hosts 127.0.0.1:1080

and it just freezes. I know in remote expert code it says wrong size input will cause such problem but I don't know where exactly the problem is. Could you please explain it? Thank you in advance!

**Comment by mryab** [comment]
Hi, thank you for your interest to this project! 

I've replicated your issue, and it seems that the default number of FFN layers in the `throughput_server` script does not fit a single 2080. Apparently, PyTorch hangs when trying to allocate this much memory, and the server does not start, hence the freezes you observed.

To solve this, try running the experiments with a reduced number of layers on a single GPU. For instance,
```
python throughput_server.py -a 32 -p 1080 --block-type ffn --gpu 0 --layers-per-gpu 4
python throughput_client.py -j 1 --batches-for-latency 5 \
    --batches-for-throughput 2 --throughput-runs 5 --linspace-points 10 \
    --layers-per-gpu 4 --block-type ffn --hosts 127.0.0.1:1080
```

By the way, the number of layers in the client and server arguments has to match; otherwise, you might either observe low GPU utilization or encounter errors when trying to query a nonexistent expert

**Comment by mryab** [comment]
I'll close the issue for now, hope my answer above helped you. If you still face any troubles when running the experiments, feel free to reopen!
